### ISSUE TITLE
Use Object.observe()

### ISSUE THREAD

**Issue by piranna** [ibc/antiglobal#1]
Make use of Object.observe() on the `window` global object listening to the 'add' change to detect when something is being added. Doing it so will have a better performance and code will be simpler since it will not be needed to poll the changes. Object.observe() is currently only available in Chrome, so it would be needed to use a polyfill like https://github.com/MaxArt2501/object-observe

**Comment by ibc** [comment]
Would be nice, but cannot be applied to `window`:

https://code.google.com/p/chromium/issues/detail?id=494574

:(

**Comment by piranna** [comment]
Security risk? Wtf?

What's the behaviour in Firefox? If it works there, maybe it could be used a polyfill on Chrome...

**Comment by ibc** [comment]
I did not test the polyfill.

**Comment by piranna** [comment]
If you have time it would be good to take it a look...
