### ISSUE TITLE
Why I need to use this package?

### ISSUE THREAD

**Issue by evandrocoan** [ibc/antiglobal#2]
I was testing a webrtc application and I found and error coming from antiglobal in the console:
![image](https://user-images.githubusercontent.com/5332158/120840372-8da65880-c540-11eb-8a4a-dafd48557725.png)

I think I kind understand what it does from the readme.md description, but I am just curious to why I would need to use this antiglobal thing.

Is there an article or something explaining why I should I use this antiglobal module?

**Comment by ibc** [comment]
You don't need to.
